// Auto-generated by scripts/compile-exemplars.mjs. Do not edit by hand.
export interface ExemplarEntry {
  id: string;
  sourceMaterial: string;
  finalArticle: string;
  tags: { contentType: string; performedWellOn: string };
}

export const exemplarRegistry: readonly ExemplarEntry[] = [];
